#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Requirements:
#    Accepts 4 parameters:
#       1. The path to the file to be transferred
#       2. The IP of the server we want to transfer the file to
#       3. The username scp connects with
#       4. The path to the SSH private key that scp uses
#    It displays:
#       Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY 
#       if less than 3 parameters passed
#    scp transfers the file to the user home directory ~/
#    Strict host key checking must be disabled since we are using scp

file_path=$1
user=$3
ip=$2
ssh_path=$4

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i /0x0B-ssh/school $file_path $user@$ip:~/
fi
