#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/@innocentsax;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
