#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
new_config="\\\n\tlocation = /redirect_me {\n"
