#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /etc/nginx/html/index.html > /dev/null
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
new_config="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53i $new_config" /etc/nginx/sites-available/default
sudo service nginx restart
