#!/usr/bin/env bash
#A Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

# Format:
#The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHE#LL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER# ID INFO

while IFS=":" read -r USERNAME PASSWORD U_ID GID FULLNAME HOME_DIRECTORY LOGIN_SHELL
do
  echo "The user $USERNAME is part of the $GID gang,\ 
  lives in $HOME_DIRECTORY and rides $LOGIN_SHELL. \
  $U_ID's place is protected by the passcode $PASSWORD, \
  more info about the user here: $FULLNAME"
done < "/etc/passwd"
